### ISSUE TITLE
Check for last x existing Daily Notes

### ISSUE THREAD

**Issue by Bluetexon** [thomasbrezinski/obsidian-nested-daily-todos#1]
Hi!
I love your plugin, but have a (hopefully small) improvement wish.

Would it be possible to change the logic of the "Number of previous days to check for todos" setting to only check the last x-Amount of **existing** Daily Notes? 

Why?
I usually have that set to 1, because I only want to rollover the todos of the previous note. Since I use it Obsidian for work, I usually do not have notes for Saturday and Sunday. That results in failing to roll over the todos on a Monday.

**Comment by thomasbrezinski** [comment]
Hi @Bluetexon, I've added a toggle to check a number of previous existing notes rather than a time range. It's available in the [1.1.0 release](https://github.com/thomasbrezinski/obsidian-nested-daily-todos/releases/tag/1.1.0) which can now be installed form the community plugins page.

**Comment by Bluetexon** [comment]
> Hi @Bluetexon, I've added a toggle to check a number of previous existing notes rather than a time range. It's available in the [1.1.0 release](https://github.com/thomasbrezinski/obsidian-nested-daily-todos/releases/tag/1.1.0) which can now be installed form the community plugins page.

Perfect! Thank you very much.
