### ISSUE TITLE
Option to remove todos from their original files (move instead of copy)

### ISSUE THREAD

**Issue by neoromantic** [thomasbrezinski/obsidian-nested-daily-todos#5]
This plugin is great for my use case and I want to replace Rollover Daily Todos with it.

However, it copies tasks, not move them: thus creating a lot of duplicates.

I can see how it may be intended: to leave a trace of "planned / not done", but for me, I need tasks to move.

Any chance it to be added?

Would you consider my PR if I add this myself?

--- 

Currently, I use https://github.com/lumoe/obsidian-rollover-daily-todos plugin and it's the same, but lacks feature to collect todos from the past, just last day.

However, they have this option:
<img width="786" alt="image" src="https://github.com/thomasbrezinski/obsidian-nested-daily-todos/assets/44672/7d100b35-b5c8-40ed-83ad-958a696fb3d2">

**Comment by neoromantic** [comment]
@thomasbrezinski any chance? :-)

**Comment by thomasbrezinski** [comment]
Hey @neoromantic, I'll take a look at adding this functionality this week.
