### ISSUE TITLE
Bringing previously completed tasks forward

### ISSUE THREAD

**Issue by robmikulec** [thomasbrezinski/obsidian-nested-daily-todos#6]
The plugin is bringing forward some tasks that were previously completed.  Again, just some of the completed tasks, not all completed tasks.

**Comment by thomasbrezinski** [comment]
Hi @robmikulec, could you share an example set of notes that demonstrates the issue?

**Comment by thomasbrezinski** [comment]
Happy to reopen with any example inputs that reproduce the issue.
