### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jcamachott** [thomasbrezinski/obsidian-nested-daily-todos#8]
Hi, I have a feature request. When I was trying out the command I thought it was not working but because I have content in my daily note already (I use a template), the tasks were getting added to the end of the file and I did not realise.

So is there a way to get the notes to be added where you have your cursor? 

Thanks.

**Comment by thomasbrezinski** [comment]
Hey @jcamachott, sorry for the delayed response.

The typical flow for someone using a template is for incomplete items to be added under the same headers they were found under in previous notes. So if you had a #Todo section with items beneath it, and a similarly named #Todo section in your template, they would automatically be added beneath the #Todo header.

It may be possible to support adding the items to the current cursor location, but currently the command can be run even when today's daily note is not open. Let me know whether the items being added under a match section header meets your needs, or we can consider the tradeoffs of only allowing inserting the items at cursor location when today's daily note is open.

Going to close the issue for now, but if we decide to implement the cursor location insertion, will reopen.
